use_frameworks!

target 'xzc_Example' do
  pod 'xzc', :path => '../'

  target 'xzc_Tests' do
    inherit! :search_paths

    pod 'Specta'
    pod 'Expecta'
    pod 'FBSnapshotTestCase'
    pod 'Expecta+Snapshots'
  end
end
